# Generated by the VisualDSP++ IDDE

# Note:  Any changes made to this Makefile will be lost the next time the
# matching project file is loaded into the IDDE.  If you wish to preserve
# changes, rename this file and run it externally to the IDDE.

# The syntax of this Makefile is such that GNU Make v3.77 or higher is
# required.

# The current working directory should be the directory in which this
# Makefile resides.

# Supported targets:
#     ale_Debug
#     ale_Debug_clean

# Define this variable if you wish to run this Makefile on a host
# other than the host that created it and VisualDSP++ may be installed
# in a different directory.

ADI_DSP=C:\Program Files (x86)\Analog Devices\VisualDSP 3.5 16-Bit

ifndef ADI_DSP_MAKE
ADI_DSP_MAKE=C:/Program\ Files\ (x86)/Analog\ Devices/VisualDSP\ 3.5\ 16-Bit
endif

# $VDSP is a gmake-friendly version of ADI_DIR

empty:=
space:= $(empty) $(empty)
VDSP_INTERMEDIATE=$(subst \,/,$(ADI_DSP))
VDSP=$(subst $(space),\$(space),$(VDSP_INTERMEDIATE))

# Define the command to use to delete files (which is different on Win95/98
# and Windows NT/2000)

ifeq ($(OS),Windows_NT)
RM=cmd /C del /F /Q
else
RM=command /C del
endif

#
# Begin "ale_Debug" configuration
#

ifeq ($(MAKECMDGOALS),ale_Debug)

ale_Debug : ./Debug/ale.dxe 

./Debug/ALE_FCT.doj :./ALE_FCT.DSP 
	$(VDSP)/easm218x.exe .\ALE_FCT.DSP -proc ADSP-2181 -g -o .\Debug\ALE_FCT.doj -MM

./Debug/ALE_IO.doj :./ALE_IO.DSP 
	$(VDSP)/easm218x.exe .\ALE_IO.DSP -proc ADSP-2181 -g -o .\Debug\ALE_IO.doj -MM

./Debug/ALE_TEST.doj :./ALE_TEST.DSP ./ale.h 
	$(VDSP)/easm218x.exe .\ALE_TEST.DSP -proc ADSP-2181 -g -o .\Debug\ALE_TEST.doj -MM

./Debug/ale.dxe :./ADSP-2181_ASM.ldf ./Debug/ALE_FCT.doj ./Debug/ALE_IO.doj ./Debug/ALE_TEST.doj $(VDSP)/218x/lib/libio.dlb $(VDSP)/218x/lib/libc.dlb $(VDSP)/218x/lib/libetsi.dlb 
	$(VDSP)/cc218x.exe .\Debug\ALE_FCT.doj .\Debug\ALE_IO.doj .\Debug\ALE_TEST.doj -T .\ADSP-2181_ASM.ldf -L .\Debug -flags-link -od,.\Debug -o .\Debug\ale.dxe -proc ADSP-2181 -flags-link -MM

endif

ifeq ($(MAKECMDGOALS),ale_Debug_clean)

ale_Debug_clean:
	$(RM) ".\Debug\ALE_FCT.doj"
	$(RM) ".\Debug\ALE_IO.doj"
	$(RM) ".\Debug\ALE_TEST.doj"
	$(RM) ".\Debug\ale.dxe"
	$(RM) ".\Debug\*.ipa"
	$(RM) ".\Debug\*.opa"
	$(RM) ".\Debug\*.ti"

endif


